config/routes.rb
Rails.application.routes.draw do
  get 'chat/:id' => 'chat#show', as: 'chat'
  devise_for :users
  resources :users,only: [:show,:edit,:update,:index] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  root 'homes#start'
  get 'homes/about' => 'homes#about'
  get 'homes/top' => 'homes#top'
  get 'homes/test' => 'homes#test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image, destroy: false
  validates :email, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length: {maximum: 50}

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  private
    #sign in後のredirect先変更
    def after_sign_in_path_for(resource)
      user_path(resource)
    end

    #sign out後のredirect先変更
    def after_sign_out_path_for(resource)
      root_path
    end

    #sin up時の登録情報追加
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profle_image, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name]) # ログイン時にnameを使用
    end
    def correct_user?(user)
      if current_user.nil?
        return false
      else
        user.id.equal?(current_user.id)
      end
    end 
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
    def show
      @user = User.find(params[:id])
      rooms = current_user.user_rooms.pluck(:room_id)
      user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
  
      unless user_rooms.nil?
        @room = user_rooms.room
      else
        @room = Room.new
        @room.save
        UserRoom.create(user_id: current_user.id, room_id: @room.id)
        UserRoom.create(user_id: @user.id, room_id: @room.id)
      end
      @chats = @room.chats
    end
  end
  

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def start
  end

  def test
  end 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
      current_user.follow(params[:user_id])
      redirect_to request.referer
    end
    
    def destroy
      current_user.unfollow(params[:user_id])
      redirect_to request.referer
    end
  
    def follower
      user = User.find(params[:user_id])
      @users = user.following_user
    end
  
    def followed
      user = User.find(params[:user_id])
      @users = user.follower_user
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :screen_user, only: [:edit, :update]
    
    def show
      @user = User.find(params[:id])
    end
  
    def index
      @users = User.all
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user)
      else
        render 'edit'
      end
    end
  
    def follows
  
    end
  
    def followers
      
    end
  
    private
      def user_params
         params.require(:user).permit(:name, :introduction, :profile_image)
      end
  
      def screen_user
        unless params[:id].to_i == current_user.id
          redirect_to user_path(current_user)
        end
      end
  
  end
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/show.html.erb
<h1 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>"><%= @user.name %> さんとのチャット</h1>

<div class="message" style="width: 400px;">
  <% @chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <p style="text-align: right;"><%= chat.message %></p>
    <% else %>
      <p style="text-align: left;"><%= chat.message %></p>
    <% end %>
  <% end %>
</div>

<input type="text" class="post">

app/views/homes/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>


app/views/homes/start.html.erb
<META http-equiv="Refresh" content="5;URL=/homes/top">

<div class="loading">
  <h1 class="animation">Now Loading...</h1>
</div>

app/views/homes/test.html.erb
<div class="page-header page-header-xs" data-parallax="true">
    <div class="filter"></div>
  </div>
  <div class="section profile-content">
    <div class="container">
      <div class="owner">
        <div class="avatar">
        <%= attachment_image_tag(current_user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg") %>
        </div>
        <div class="name">
          <h4 class="title">Jane Faker
            <br />
          </h4>
          <h6 class="description">Music Producer</h6>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 ml-auto mr-auto text-center">
          <p>An artist of considerable range, Jane Faker — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. </p>
          <br />
          <btn class="btn btn-outline-default btn-round"><i class="fa fa-cog"></i> Settings</btn>
        </div>
      </div>
      <br/>
      <div class="nav-tabs-navigation">
        <div class="nav-tabs-wrapper">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#follows" role="tab">Follows</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#following" role="tab">Following</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- Tab panes -->
      <div class="tab-content following">
        <div class="tab-pane active" id="follows" role="tabpanel">
          <div class="row">
            <div class="col-md-6 ml-auto mr-auto">
              <ul class="list-unstyled follows">
                <li>
                  <div class="row">
                    <div class="col-lg-2 col-md-4 col-4 ml-auto mr-auto">
                      <img src="../../assets/images/faces/clem-onojeghuo-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                    </div>
                    <div class="col-lg-7 col-md-4 col-4  ml-auto mr-auto">
                      <h6>Flume
                        <br/>
                        <small>Musical Producer</small>
                      </h6>
                    </div>
                    <div class="col-lg-3 col-md-4 col-4  ml-auto mr-auto">
                      <div class="form-check">
                        <label class="form-check-label">
                          <input class="form-check-input" type="checkbox" value="" checked>
                          <span class="form-check-sign"></span>
                        </label>
                      </div>
                    </div>
                  </div>
                </li>
                <hr />
                <li>
                  <div class="row">
                    <div class="col-lg-2 col-md-4 col-4 mx-auto ">
                      <img src="../../assets/images/faces/ayo-ogunseinde-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                    </div>
                    <div class="col-lg-7 col-md-4 col-4">
                      <h6>Banks
                        <br />
                        <small>Singer</small>
                      </h6>
                    </div>
                    <div class="col-lg-3 col-md-4 col-4">
                      <div class="form-check">
                        <label class="form-check-label">
                          <input class="form-check-input" type="checkbox" value="">
                          <span class="form-check-sign"></span>
                        </label>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="tab-pane text-center" id="following" role="tabpanel">
          <h3 class="text-muted">Not following anyone yet :(</h3>
          <button class="btn btn-warning btn-round">Find artists</button>
        </div>
      </div>
    </div>
  </div>

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to 'Log in',new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>
            
  </div>
</div>
        

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar-expand-lg fixed-top navbar-transparent " color-on-scroll="300">
<div class="container">
  <div class="navbar-translate">
    <a class="navbar-brand" href="https://demos.creative-tim.com/paper-kit/index.html" rel="tooltip" title="Coded by Creative Tim" data-placement="bottom" target="_blank">
      Paper Kit 2
    </a>
    <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-bar bar1"></span>
      <span class="navbar-toggler-bar bar2"></span>
      <span class="navbar-toggler-bar bar3"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse justify-content-end" id="navigation">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="../index.html" class="nav-link"><i class="nc-icon nc-layout-11"></i> ここにナビリスト追加</a>
      </li>
      <li class="nav-item">
        <a href="../index.html" class="nav-link"><i class="nc-icon nc-layout-11"></i> Components</a>
      </li>
      <li class="nav-item">
        <a href="https://demos.creative-tim.com/paper-kit-2/docs/1.0/getting-started/introduction.html" target="_blank" class="nav-link"><i class="nc-icon nc-book-bookmark"></i> Documentation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" rel="tooltip" title="Follow us on Twitter" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank">
          <i class="fa fa-twitter"></i>
          <p class="d-lg-none">Twitter</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" rel="tooltip" title="Like us on Facebook" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank">
          <i class="fa fa-facebook-square"></i>
          <p class="d-lg-none">Facebook</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" rel="tooltip" title="Follow us on Instagram" data-placement="bottom" href="https://www.instagram.com/CreativeTimOfficial" target="_blank">
          <i class="fa fa-instagram"></i>
          <p class="d-lg-none">Instagram</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" rel="tooltip" title="Star on GitHub" data-placement="bottom" href="https://www.github.com/CreativeTimOfficial" target="_blank">
          <i class="fa fa-github"></i>
          <p class="d-lg-none">GitHub</p>
        </a>
      </li>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <!-- fontawesome用 -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  　<link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      	<%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relationships/followed.html.erb
<h2>Follower Users</h2>
<% if @users.count > 0 %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/follower.html.erb
<h2>Follow Users</h2>
<% if @users.count > 0 %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, format: 'jpeg', size: "30x30", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.follower.count %></td>
        <td>フォロワー数：<%= user.followed.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.follower.count, user_follows_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followed.count, user_followers_path(user) %></th>
  </tr>
</table>
<!-- フォローボタン -->
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
  <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
  <% end %>
<% end %>

  <div class='row'>
    <%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
  </div>

<% if current_user != user %>
  <%= link_to 'チャットを始める', chat_path(user.id) %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>

    <h2>New book</h2>


  </div>

  <div class='col-xs-9'>
    <h2>Users</h2>

    <%= render 'index',users: @users %>
  </div>

</div>

app/views/users/show.html.erb
<div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: @user,now: ''%>

    <h2>New book</h2>


  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

   
  </div>
</div>